apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: {{ .Values.deployment.repo }}/{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        name: guestbook-ui
        ports:
        - containerPort: {{ .Values.deployment.port }}
