apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  type:  {{ .Values.svc.type }}
  ports:
    - name: http
      port: {{ .Values.svc.port }}
      targetPort: {{ .Values.svc.targetPort }}
  selector:
    app: guestbook-ui
