apiVersion: v1
kind: Pod
metadata:
  name: cuda-test
spec:
  containers:
    - name: cuda-test
      image: "yanivomc/spring-music:latest"
  nodeSelector:
    env: prod

# When applied, this will be pending until a node is labeled with env=prod
# e.g. kubectl label node/davamart-m03 env=prod
