apiVersion: v1
kind: Service
metadata:
  name: pod-service
  labels:
    app: 20220328-lab02
spec:
  type: LoadBalancer
  selector:
    app: 20220328-lab02
  ports:
  - name: mysql
    protocol: TCP
    port: 8080
    targetPort: 80
