deployment:
  replicas: 4
  repo: gcr.io/heptio-images
  image: ks-guestbook-demo
  tag: 0.2
  port: 8080  # container port
service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080  # container port
