apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: my-datavolume
          persistentVolumeClaim:
            claimName: nfs-pvc

        # - name: my-datavolume
        #   nfs: 
        #     # URL for the NFS server
        #     server: rletigre # Change this!
        #     path: /nfsshare/mysql
        # mountOptions:
        #   - rw
        #   - nfsvers=3

        # - name: my-datavolume
        #   persistentVolumeClaim:
        #     claimName: task-pv-claim
      # volumes:
      # - name: my-datavolume
      #   #emptyDir: {}
      #   persistentVolumeClaim:
      #     claimName: db-pvc
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: db-password
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: my-datavolume
