apiVersion: v1
kind: Pod
metadata:
  name: mysql-admin
  labels:
   role: sqladmin
spec:
      containers:
      - name: mysql
        image: mysql:5.7
        args: ["sleep", "36000"]
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: db-password
