apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Delete
  storageClassName: local-sc
  local:
    path: /home/rletigre/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - usendavalrl1c
          - davalos
          - davalos-m02
          - davalos-m03

