kind: Service      # Create new service
apiVersion: v1
metadata:
  name: wordpress-service # Name of the service
spec:
  type: NodePort
  # type: LoadBalancer
  selector:
    app: wordpress
  ports:          # Map incoming port to target port
  - name: http-web    # Setting multiple ports listterns
    protocol: TCP
    port: 80
    targetPort: 80
