kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: db-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: "slow-io"
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 4Gi
